<template>
  <div>
    <Nav v-on:goMenu="onGoMenu" />

    <!-- Header -->
    <header class="masthead bg-primary text-white text-center">
      <div class="container">
        <!-- <img class="img-fluid mb-5 d-block mx-auto" src="img/profile.png" alt=""> -->
        <h1 class="text-uppercase mb-0">Start Avarkey</h1>
        <hr class="star-light">
        <h2 class="font-weight-light mb-0">Generate a unique avatar from a public key</h2>
      </div>
    </header>    

    <!-- generate Section -->
    <section id="generate">
      <div class="container">
        <h2 class="text-center text-uppercase text-secondary mb-0">Generate avarkey</h2>
        <hr class="star-dark mb-5">        
        <Gavarkey />
      </div>
    </section>


    <!-- Portfolio Grid Section -->
    <section class="portfolio" id="portfolio">
      <div class="container">
        <h2 class="text-center text-uppercase text-secondary mb-0">PortFolio</h2>
        <hr class="star-dark mb-5">
        <Portfolio />
      </div>
    </section>

    <!-- About Section -->
    <section class="bg-primary text-white mb-0" id="about">
      <div class="container">
        <h2 class="text-center text-uppercase text-white">About</h2>
        <hr class="star-light mb-5">
        <div class="row">
          <div class="col-lg-4 ml-auto">
            <p class="lead">Generating Identicon with NFT(Non Fungible Token). Each identicon can be generated by user’s painting within a square grid system and non-fungible. It connect with user’s address and unique account name.</p>
          </div>
          <div class="col-lg-4 mr-auto">
            <p class="lead">Avarkey is a unique shaped avatar that is generated using a user's own public key. Your avarkey is unique, no one has the same avarkey as you.</p>
          </div>
        </div>
        <div class="text-center mt-4">
          <a class="btn btn-xl btn-outline-light" href="#" v-scroll-to="{ element: '#generate', easing: 'linear' }">
            <i class="fas fa-download mr-2"></i>
            Try it Now!
          </a>
        </div>
      </div>
    </section>

    <!-- Contact Section -->
    <section id="contact">
      <div class="container">
        <h2 class="text-center text-uppercase text-secondary mb-0">Register your email</h2>
        <hr class="star-dark mb-5">
        <div class="row">
          <div class="col-lg-8 mx-auto">            
            <form name="sentMessage" id="contactForm" novalidate="novalidate" @submit.prevent="registerEmail">              
              <div class="control-group">
                <div class="form-group floating-label-form-group controls mb-0 pb-2">
                  <label>Email</label>
                  <input class="form-control" id="email" type="email" placeholder="Email Address" required="required" data-validation-required-message="Please enter your email address." v-model="email">
                  <p class="help-block text-danger"></p>
                </div>
              </div>                            
              <div id="success"></div>
              <div class="form-group">
                <button type="submit" class="btn btn-primary btn-xl" id="sendMessageButton">Send</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="footer text-center">
      <div class="container">
        <div class="row">
          <div class="col-md-4 mb-5 mb-lg-0">
            <h4 class="mb-4">EpitomeCL</h4>            
            <h6>Creators</h6>
          </div>
          <div class="col-md-4 mb-5 mb-lg-0">            
            <ul class="list-inline mb-0">
              <li class="list-inline-item">
                <img class="fab" src="/facebook.png" alt="">
              </li>
              <li class="list-inline-item">
                <img class="fab" src="/twitter.png" alt="">
              </li>
              <li class="list-inline-item">
                <img class="fab" src="/telegram.png" alt="">
              </li>              
              <li class="list-inline-item">
                <img class="fab" src="/gmail.png" alt="">
              </li>              
            </ul>
          </div>
          <div class="col-md-4">
            <!-- <h4 class="text-uppercase mb-4">About Freelancer</h4>
            <p class="lead mb-0">Freelance is a free to use, open source Bootstrap theme created by
              <a href="http://startbootstrap.com">Start Bootstrap</a>.</p> -->
          </div>
        </div>
      </div>
    </footer>

    <div class="copyright py-4 text-center text-white">
      <div class="container">
        <small>Copyright &copy; EpitomeCL 2018</small>
      </div>
    </div>
  </div>
</template>

<script>
import firebase from 'firebase'
import firebaseStore from 'firebase/firestore'
import Nav from '~/components/landing/Nav.vue'
import Gavarkey from '~/components/landing/Gavarkey.vue'
import Portfolio from '~/components/landing/Portfolio.vue'


export default {
  components: {
    Nav,
    Gavarkey,
    Portfolio
  },

  data() {
    return {
      email: null
    }
  },

  computed: {
    validation: function () {
      const emailRE = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
      return {        
        email: emailRE.test(this.email)
      }
    },
    isValid: function () {
      const validation = this.validation
      return Object.keys(validation).every(function (key) {
        return validation[key]
      })
    }
  },

  mounted() {    
    const config = {
      apiKey: "AIzaSyCsVi15QQTbjtEYkl0nAiIxqldW3hU1orM",
      authDomain: "avarkey-bb036.firebaseapp.com",
      databaseURL: "https://avarkey-bb036.firebaseio.com",
      projectId: "avarkey-bb036",
      storageBucket: "",
      messagingSenderId: "725374065200"
    };
    firebase.initializeApp(config);
  },

  methods: {
    onGoMenu(hash) {      
      if(hash){
        this.$scrollTo(`#${hash}`, 500, {offset: -60})                
      }
    },

    registerEmail() {
      if(this.isValid){
        const db = firebase.firestore()
        db.collection("emails").add({
          email: this.email
        })
        .then((docRef) => {
          console.log("savedId:", docRef.id)
          alert("Email registration completed..!")
          this.email = null
        })
        .catch((error) => {
          console.error("error:", error)
        })          
      } else {
        alert("please confirm your email correctly")
      }      
    }
  }  
}
</script>
<style scoped>

.bg-primary {
  background-color: #6ca8e8 !important;
}

section {
  padding: 6rem 0;
}

section h2 {
  font-size: 2.25rem;
  line-height: 2rem;
}

@media (min-width: 992px) {
  section h2 {
    font-size: 3rem;
    line-height: 2.5rem;
  }
}


header.masthead {
  padding-top: calc(6rem + 72px);
  padding-bottom: 6rem;
}

header.masthead h1 {
  font-size: 3rem;
  line-height: 3rem;
}

header.masthead h2 {
  font-size: 1.3rem;
  font-family: 'Lato';
}

@media (min-width: 992px) {
  header.masthead {
    padding-top: calc(6rem + 106px);
    padding-bottom: 6rem;
  }
  header.masthead h1 {
    font-size: 4.75em;
    line-height: 4rem;
  }
  header.masthead h2 {
    font-size: 1.75em;
  }
}


.portfolio {
  margin-bottom: -15px;
}


@media (min-width: 576px) {
  .portfolio {
    margin-bottom: -30px;
  }  
}

.fab {
  width: 32px;
  cursor: pointer;
}


.footer {
  padding-top: 5rem;
  padding-bottom: 5rem;
  background-color: #2C3E50;
  color: #fff;
}

.copyright {
  background-color: #1a252f;
}


</style>